include kitty-base.conf

# macOS: hide titlebar
hide_window_decorations titlebar-only

# macOS: slightly transparent background
background_opacity 0.97

# macOS keybindings
map cmd+t       new_tab
map cmd+left    previous_tab
map cmd+right   next_tab

allow_remote_control yes
update_title no
shell_integration enabled
